name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore: [".git**"]
  workflow_dispatch:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        id: setup-postgres
        uses: alphagov/govuk-infrastructure/.github/actions/setup-postgres@main

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rails db:setup
        env:
          RAILS_ENV: test

      - run: bundle exec rake spec
        env:
          RAILS_ENV: test
